import type { Preset } from '@/types';

export const PRESETS: Preset[] = [
  // ===================== LLM / Transformer =====================
  { name: 'LLaMA 3 8B', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'LLaMA 3 8B', parameters: 8e9, layers: 32, hiddenSize: 4096, heads: 32, contextLength: 4096 }, trainingConfig: { datasetSize: 1e9, batchSize: 4, epochs: 1, precision: 'fp16', gradientAccumulation: 8 }, hardwareConfig: { gpuVram: 32, gpuTflops: 312, ram: 64, cpuCores: 16 } },
  { name: 'LLaMA 70B', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'LLaMA 70B', parameters: 70e9, layers: 80, hiddenSize: 8192, heads: 64, contextLength: 4096 }, trainingConfig: { datasetSize: 2e9, batchSize: 2, epochs: 1, precision: 'fp16', gradientAccumulation: 16 }, hardwareConfig: { gpuVram: 80, gpuTflops: 624, ram: 256, cpuCores: 64 } },
  { name: 'GPT-2 Small (124M)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'GPT-2 Small', parameters: 124e6, layers: 12, hiddenSize: 768, heads: 12, contextLength: 1024 }, trainingConfig: { datasetSize: 500e6, batchSize: 8, epochs: 1, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'GPT-2 XL (1.5B)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'GPT-2 XL', parameters: 1.5e9, layers: 48, hiddenSize: 1600, heads: 25, contextLength: 1024 }, trainingConfig: { datasetSize: 1e9, batchSize: 4, epochs: 1, precision: 'fp16', gradientAccumulation: 8 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'Mistral 7B', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'Mistral 7B', parameters: 7e9, layers: 32, hiddenSize: 4096, heads: 32, contextLength: 8192 }, trainingConfig: { datasetSize: 2e9, batchSize: 4, epochs: 1, precision: 'fp16', gradientAccumulation: 8 }, hardwareConfig: { gpuVram: 48, gpuTflops: 330, ram: 128, cpuCores: 32 } },
  { name: 'Phi-3 Mini (3.8B)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'Phi-3 Mini', parameters: 3.8e9, layers: 32, hiddenSize: 3072, heads: 32, contextLength: 4096 }, trainingConfig: { datasetSize: 1e9, batchSize: 4, epochs: 1, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'Gemma 2B', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_decoder', modelName: 'Gemma 2B', parameters: 2e9, layers: 18, hiddenSize: 2048, heads: 8, contextLength: 8192 }, trainingConfig: { datasetSize: 500e6, batchSize: 8, epochs: 1, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'BERT Base (110M)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_encoder', modelName: 'BERT Base', parameters: 110e6, layers: 12, hiddenSize: 768, heads: 12, contextLength: 512 }, trainingConfig: { datasetSize: 3.3e9, batchSize: 32, epochs: 3, precision: 'fp16', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'BERT Large (340M)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_encoder', modelName: 'BERT Large', parameters: 340e6, layers: 24, hiddenSize: 1024, heads: 16, contextLength: 512 }, trainingConfig: { datasetSize: 3.3e9, batchSize: 16, epochs: 3, precision: 'fp16', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'T5 Base (220M)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_encoder_decoder', modelName: 'T5 Base', parameters: 220e6, layers: 12, hiddenSize: 768, heads: 12, contextLength: 512 }, trainingConfig: { datasetSize: 1e9, batchSize: 16, epochs: 1, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'T5 Large (770M)', category: 'LLM / Transformer', modelConfig: { modelType: 'transformer_encoder_decoder', modelName: 'T5 Large', parameters: 770e6, layers: 24, hiddenSize: 1024, heads: 16, contextLength: 512 }, trainingConfig: { datasetSize: 1e9, batchSize: 8, epochs: 1, precision: 'fp16', gradientAccumulation: 8 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'Mixtral 8x7B (MoE)', category: 'LLM / Transformer', modelConfig: { modelType: 'moe', modelName: 'Mixtral 8x7B', parameters: 46.7e9, layers: 32, hiddenSize: 4096, heads: 32, contextLength: 32768, numExperts: 8, activeExperts: 2 }, trainingConfig: { datasetSize: 2e9, batchSize: 2, epochs: 1, precision: 'fp16', gradientAccumulation: 16 }, hardwareConfig: { gpuVram: 80, gpuTflops: 624, ram: 256, cpuCores: 64 } },

  // ===================== Vision / CNN ==========================
  { name: 'ResNet-50', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'ResNet-50', parameters: 25.6e6, layers: 50, hiddenSize: 2048, heads: 1, contextLength: 224 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 32, epochs: 90, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 24, gpuTflops: 82, ram: 64, cpuCores: 16 } },
  { name: 'ResNet-152', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'ResNet-152', parameters: 60.2e6, layers: 152, hiddenSize: 2048, heads: 1, contextLength: 224 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 16, epochs: 90, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 24, gpuTflops: 82, ram: 64, cpuCores: 16 } },
  { name: 'VGG-16', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'VGG-16', parameters: 138e6, layers: 16, hiddenSize: 4096, heads: 1, contextLength: 224 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 16, epochs: 90, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 24, gpuTflops: 82, ram: 64, cpuCores: 16 } },
  { name: 'EfficientNet-B7', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'EfficientNet-B7', parameters: 66e6, layers: 55, hiddenSize: 2560, heads: 1, contextLength: 600 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 8, epochs: 100, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'YOLOv8-L', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'YOLOv8-L', parameters: 43.7e6, layers: 53, hiddenSize: 1024, heads: 1, contextLength: 640 }, trainingConfig: { datasetSize: 118e3, batchSize: 16, epochs: 300, precision: 'fp16', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'ConvNeXt-Base', category: 'Vision / CNN', modelConfig: { modelType: 'cnn', modelName: 'ConvNeXt-Base', parameters: 89e6, layers: 36, hiddenSize: 1024, heads: 1, contextLength: 224 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 32, epochs: 300, precision: 'fp16', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },

  // ===================== Sequence / RNN ========================
  { name: 'Vanilla RNN (Small)', category: 'Sequence / RNN', modelConfig: { modelType: 'rnn', modelName: 'Vanilla RNN', parameters: 5e6, layers: 2, hiddenSize: 512, heads: 1, contextLength: 256 }, trainingConfig: { datasetSize: 50e6, batchSize: 64, epochs: 10, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 8, gpuTflops: 65, ram: 16, cpuCores: 8 } },
  { name: 'Vanilla RNN (Large)', category: 'Sequence / RNN', modelConfig: { modelType: 'rnn', modelName: 'Vanilla RNN Large', parameters: 50e6, layers: 4, hiddenSize: 1024, heads: 1, contextLength: 512 }, trainingConfig: { datasetSize: 200e6, batchSize: 32, epochs: 5, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'LSTM (Small)', category: 'Sequence / RNN', modelConfig: { modelType: 'lstm', modelName: 'LSTM Small', parameters: 10e6, layers: 2, hiddenSize: 512, heads: 1, contextLength: 256 }, trainingConfig: { datasetSize: 50e6, batchSize: 64, epochs: 10, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 8, gpuTflops: 65, ram: 16, cpuCores: 8 } },
  { name: 'LSTM (Large)', category: 'Sequence / RNN', modelConfig: { modelType: 'lstm', modelName: 'LSTM Large', parameters: 100e6, layers: 4, hiddenSize: 1024, heads: 1, contextLength: 512 }, trainingConfig: { datasetSize: 200e6, batchSize: 32, epochs: 5, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'LSTM Seq2Seq', category: 'Sequence / RNN', modelConfig: { modelType: 'lstm', modelName: 'LSTM Seq2Seq', parameters: 60e6, layers: 6, hiddenSize: 1024, heads: 1, contextLength: 512 }, trainingConfig: { datasetSize: 100e6, batchSize: 32, epochs: 15, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'GRU (Small)', category: 'Sequence / RNN', modelConfig: { modelType: 'gru', modelName: 'GRU Small', parameters: 8e6, layers: 2, hiddenSize: 512, heads: 1, contextLength: 256 }, trainingConfig: { datasetSize: 50e6, batchSize: 64, epochs: 10, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 8, gpuTflops: 65, ram: 16, cpuCores: 8 } },
  { name: 'GRU (Large)', category: 'Sequence / RNN', modelConfig: { modelType: 'gru', modelName: 'GRU Large', parameters: 80e6, layers: 4, hiddenSize: 1024, heads: 1, contextLength: 512 }, trainingConfig: { datasetSize: 200e6, batchSize: 32, epochs: 5, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },

  // ===================== Generative ============================
  { name: 'Stable Diffusion 1.5', category: 'Generative', modelConfig: { modelType: 'diffusion', modelName: 'Stable Diffusion 1.5', parameters: 860e6, layers: 16, hiddenSize: 1280, heads: 8, contextLength: 512 }, trainingConfig: { datasetSize: 2e9, batchSize: 4, epochs: 1, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'Stable Diffusion XL', category: 'Generative', modelConfig: { modelType: 'diffusion', modelName: 'SDXL', parameters: 3.5e9, layers: 24, hiddenSize: 2048, heads: 16, contextLength: 1024 }, trainingConfig: { datasetSize: 2e9, batchSize: 2, epochs: 1, precision: 'fp16', gradientAccumulation: 8 }, hardwareConfig: { gpuVram: 48, gpuTflops: 330, ram: 128, cpuCores: 32 } },
  { name: 'StyleGAN3', category: 'Generative', modelConfig: { modelType: 'gan', modelName: 'StyleGAN3', parameters: 30e6, layers: 14, hiddenSize: 512, heads: 1, contextLength: 1024 }, trainingConfig: { datasetSize: 70e3, batchSize: 8, epochs: 500, precision: 'fp32', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
  { name: 'DCGAN', category: 'Generative', modelConfig: { modelType: 'gan', modelName: 'DCGAN', parameters: 3.5e6, layers: 5, hiddenSize: 256, heads: 1, contextLength: 64 }, trainingConfig: { datasetSize: 70e3, batchSize: 128, epochs: 200, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 8, gpuTflops: 65, ram: 16, cpuCores: 8 } },
  { name: 'VAE (Image)', category: 'Generative', modelConfig: { modelType: 'vae', modelName: 'VAE Image', parameters: 15e6, layers: 8, hiddenSize: 512, heads: 1, contextLength: 256 }, trainingConfig: { datasetSize: 60e3, batchSize: 64, epochs: 100, precision: 'fp32', gradientAccumulation: 1 }, hardwareConfig: { gpuVram: 8, gpuTflops: 65, ram: 16, cpuCores: 8 } },
  { name: 'VQ-VAE-2', category: 'Generative', modelConfig: { modelType: 'vae', modelName: 'VQ-VAE-2', parameters: 40e6, layers: 12, hiddenSize: 512, heads: 1, contextLength: 256 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 32, epochs: 50, precision: 'fp16', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },

  // ===================== Other =================================
  { name: 'ViT-Base (Vision Transformer)', category: 'Other', modelConfig: { modelType: 'transformer_encoder', modelName: 'ViT-Base', parameters: 86e6, layers: 12, hiddenSize: 768, heads: 12, contextLength: 224 }, trainingConfig: { datasetSize: 1.28e6, batchSize: 32, epochs: 90, precision: 'fp16', gradientAccumulation: 2 }, hardwareConfig: { gpuVram: 16, gpuTflops: 130, ram: 32, cpuCores: 8 } },
  { name: 'Whisper Medium', category: 'Other', modelConfig: { modelType: 'transformer_encoder_decoder', modelName: 'Whisper Medium', parameters: 769e6, layers: 24, hiddenSize: 1024, heads: 16, contextLength: 1500 }, trainingConfig: { datasetSize: 680e3, batchSize: 8, epochs: 3, precision: 'fp16', gradientAccumulation: 4 }, hardwareConfig: { gpuVram: 24, gpuTflops: 165, ram: 64, cpuCores: 16 } },
];
